scalar Upload

input PhotoUpload {
  photo: Upload!
}

type Photo {
  id: String!
  src: String!
  description: String
  tags: [String]
}

type Query {
  photo(id: String!): Photo!
  photos: [Photo!]!
}

type Mutation {
  addPhoto(data: PhotoUpload!): Photo!
}
